### ISSUE TITLE
from_name option is not respected

### ISSUE THREAD

**Issue by ntmlod** [trac-hacks/trac-wikinotification#9] opened 2016-01-27 21:29 UTC
Hi,

Last days, I download your plugin and install it in the Trac environment of our project (1.0.1).

The plugin sends the notification message but the trouble I have is that my setting of `from_name` is not taken into account. Instead I get the setting of `smtp_from_name` variable from `[notification]` section.

The addition of a `smtp_from_name` setting in `[wiki-notification]` does not even work.

Regards

**Comment by rjollos** [comment] 2016-01-28 18:21
> Instead I get the setting of `smtp_from_name` variable from `[notification]` section.

That could be coincidental. Have you tried changing `smtp_from_name` to confirm that `from_name` changes accordingly? I don't see a problem with `from_name` in the code. `smtp_from_name` is not defined or used by trac-wikinotification.

**Comment by ntmlod** [comment] 2016-01-29 15:58
I made some logical tests:
- `wiki-notification.from_name` not set & `notification.smtp_from_name` not set
=> the email has `project.name` for author so as expected for the default behavior
- `wiki-notification.from_name` set & `notification.smtp_from_name` not set
=> the email has `project.name` for author
- `wiki-notification.from_name` set & `notification.smtp_from_name` set
=> the email has `notification.smtp_from_name` for author
- `wiki-notification.from_name` not set & `notification.smtp_from_name` set
=> the email has `notification.smtp_from_name` for author

I conclude that `wiki-notification.from_name` has not effect and `notification.smtp_from_name` replaces in its role.

**Comment by mitar** [comment] 2016-06-02 11:43
I cleaned code a bit around this. Not sure if it helps, but now I do not see why it would not work. Please test.

**Comment by ntmlod** [comment] 2016-07-11 16:08
Update the plugin to the last version 0.4.2 but still the same behaviour.

It's a bit weird because I have defined 3 custom settings in [wiki-notification] section: `from_name` is the only one not taking into account unlike `smtp_always_bcc` and `subject_template`

**Comment by mitar** [comment] 2016-07-11 17:38
Have you tried to configure it through an admin interface?

**Comment by ntmlod** [comment] 2016-07-11 17:44
Due to the configuration of the Trac installation (Apache not allowed to modify), I edit directly trac.ini.

**Comment by mitar** [comment] 2016-07-11 17:45
Do you restart Trac after you edit trac.ini?

**Comment by ntmlod** [comment] 2016-07-11 17:54
What do you mean by restarting Trac ? Some stuff with `trac-admin` command or you are talking about the web server ? In fact I'm not the admin of the server and fortunately I never have to restart Apache after the installation of a plugin.

**Comment by mitar** [comment] 2016-07-11 17:59
Hm, you should check how you run Trac. You should restart it process, or restart Apache, or both. Try it and see if it works.

**Comment by ntmlod** [comment] 2016-07-11 18:56
Ok, I'll see with our local admin and get back after.

**Comment by rjollos** [comment] 2016-07-11 19:44
Trac will autodetect a change in trac.ini and reload the file, so it's never necessary to restart the webserver due to a change in trac.ini. I've found it's usually necessary to restart the webserver after installing or updating a plugin though.

**Comment by mitar** [comment] 2016-07-11 19:45
@rjollos: The reason why I am considering this is because of this line: https://github.com/trac-hacks/trac-wikinotification/blob/master/WikiNotification/notification.py#L101

Not sure if this gets reloaded as well.

**Comment by rjollos** [comment] 2016-07-11 20:20
Yeah, it should be fine. Even if that attribute were lazily-evaluated (which it's not), the `Environment` object is re-created whenever a [change in trac.ini is detected](https://trac.edgewall.org/browser/tags/trac-1.0.11/trac/env.py?marks=936-943#L914). `open_environment` is called near the start of the request handling in `trac.web.main`.

**Comment by mitar** [comment] 2016-07-11 20:22
OK. Then I do not know anymore what could be wrong.

**Comment by rjollos** [comment] 2016-07-11 20:35
What other plugins are installed in the environment?

**Comment by ntmlod** [comment] 2016-07-12 08:47
I have a lot (~50 in all) so I don't see which one I can point.
But I have a similar feature with WorkflowNotificationPlugin for tickets, no customized settings  for the email sender but, following the installation instructions, I add `ConfigurableTicketWorkflow` before `TicketWorkflowNotifier` for `workflow` in `[ticket]`.
Hope this help.

**Comment by mitar** [comment] 2017-06-11 06:44
Closing this because it was not possible to reproduce it.

**Comment by rjollos** [comment] 2017-06-11 10:20
I can reproduce. The `from_name` is re-assigned in [NotifyEmail.notify](https://github.com/trac-hacks/trac-wikinotification/blob/master/WikiNotification/notification.py#L154).

**Closed** 2017-06-11 10:34 UTC
